baseURL = "https://runthem.org/"
# 我的域名, 没有也没有访问, 是说明性实例, 可填可不填
languageCode = "zh-CN"
# 语言环境, 不然就是英文了
title = "Blog"
# 网站的名字
paginate = 12
# 每页12份文章, 翻页
theme = "m10c"
# 指定主题


[params]
	author = ""
	avatar = "2.jpg"
	description = "啊哈哈哈哈"	#描述
	# customCSS = ["prism.css"]
	# customJS = ["prism.js"]
	pygmentsUseClasses = true

[[params.social]]
	name = "github"
	url = "https://github.com/ChinaXhm"

[[params.social]]
	name = "mail"
	# url = "mailto:iccy.fun@gmail.com"
	url = "mailto:2268234697@qq.com"
